### ISSUE TITLE
Exclamation points with a space before at the end of a phrase trigger Markdown-Notice

### ISSUE THREAD

**Issue by Romarain** [getgrav/grav-plugin-markdown-notices#13]
I've come into a but involving that Markdown-Notice was showing itself in some random pages of my project. The markdown causing the bug to occur was like this one :

```
Nous avons le plaisir de vous accueillir sur notre tout nouveau site, désormais plus rapide, avec plus de fonctionnalités ! Plus d'infos [ici](/actualites/nouveau-site).
```
Making the link to be partially converted, and wrapped into a markdown notice : 

![2019-09-09_23h37m40s_firefox](https://user-images.githubusercontent.com/22033256/64568369-da083880-d35a-11e9-8356-8289da2d39c8.jpg)

After a few debugging, I suspected and confirmed Markdown-Notice's fault. 

But this is just by pure intuition about the use of `!` at the *begining* of blocks to use the plugin, that I said to myself **that it could be any exclamation point in a phrase** that would trigger the plugin, **if preceeded by a space**.

So I tried to remove the space, like in american standards : 

```
Nous avons le plaisir de vous accueillir sur notre tout nouveau site, désormais plus rapide, avec plus de fonctionnalités! Plus d'infos [ici](/actualites/nouveau-site).
```
and the bug disappeard !

### Conclusion

It seems that the plugin does not restrict itself to searching for "!" in the begining of lines, wich causes any "!" to be captured if a space *separates it* from the rest of the string.

My intuition says me that is is a problem of RegEx...

**Comment by rhukster** [comment]
This was introduced as part of this PR: https://github.com/getgrav/grav-plugin-markdown-notices/commit/d1d28f4f492f1090a45ecea32e438a2513f44983

Basically it allows to use markdown notices that don't start at the beginning of the line.  Because a single `!` triggers a markdown notice, it will consider anything with `<space>!<space>` as a markdown notice.

**Comment by Romarain** [comment]
Ok @rhukster, but how can we solve the problem ? Because european standard implies to use spaces before semicolons and exclamation or interrogation points. In the context of using Grav to develop commercial websites, it will be difficult to avoid customers using those spaces.
I know that the quick solution would be to disable the plugin, but couldn't we just adapt the PHP regEx so it :
1. Search for `!` at the begining of a line.
2. Or search `!` preceeded by `|<space>`, and not only `<space>` ?

I'm actually trying to decode the PHP of the plugin, in order to see what I can do to change : 

```
            if (preg_match('/^(!{1,'.count($this->level_classes).'})[ ]+(.*)/', $Line['text'], $matches))
```
by something more adapted.

**Comment by Romarain** [comment]
I found a regular expression that could match the markdown table configuration : 
https://regex101.com/r/nTg60a/1

![2019-09-10_00h50m44s_chrome](https://user-images.githubusercontent.com/22033256/64571946-c3b3aa00-d365-11e9-8188-d0b5fd3a7b8c.jpg)

**Comment by rhukster** [comment]
Looks good to me.  How about a PR?

**Comment by Romarain** [comment]
@rhukster 
My competences are limited.
I think I've found the correct PHP regex : 
```php
            $foundedMatches = preg_match_all('/([|][^\n])[ ]*(!{1,'.count($this->level_classes).'})[ ]([^|<>\n]+)/', $Line['text'], $matches);
```
but the problem is the rest of the code need to be adapted (capturing parenthesis references, **wich is number 3 now, and not 2 anymore**) so is correctly get the text following the `!`. And I don't see what's going on in : 
```php
            if ( $foundedMatches > 0 )
            {
                $level = strlen( $matches[1][0] ) - 1;

                // if we have more levels than we support
                if ( $level > count( $this->level_classes ) - 1 )
                {
                    return;
                }

                $preText = explode( $Line['text'], $Line['context'], 2 );

                if ( strpos($Line['context'], $Line['text']) === 0 || rtrim( $preText[0] ) !== $preText[0] )
                {
                    $Block = [
                        'extent' => strlen( $matches[0][0] ),
                        'element' => [
                            'name' => 'div',
                            'text' => $matches[2][0],
                            'attributes' => [
                                'class' => 'notices ' . $this->level_classes[ $level ],
                            ],
                        ],
                    ];
```

**Comment by Romarain** [comment]
I have news.
I found that the RegEx I was working on was rejected not because of its syntax, but because the string observed by the RegEx wasn't the one I thought.

Indeed, `$Line['text']`, when dumped with `$this->grav['debugger']->addMessage($Line['text']);` under the block
```
        $markdown->inlineNotices = function($Line)
        {
```
is returning _(for the table given as example)_ : 
![2019-09-10_14h47m32s_firefox](https://user-images.githubusercontent.com/22033256/64618842-4cbbf700-d3e1-11e9-93e5-a5dc625a93a2.jpg)

So it means that the _plugin_ receive an **incomplete raw data** from the _markdown engine_. 
It should be : 
```
| ! Information here
| !!! Note here
| !!!! Warning here
```
so the RegEx can capture the `|` at the begining. I don't even understand why it seems to output a parsing of the iterative `!` preceeding the text.

### Consequently

In the actual context, the ReGex 
`/(\|[^\n])[ ]*(!{1,'.count($this->level_classes).'})[ ]([^|<>\n]+)/` 
is useless, but more suprisingly, the original RegEx 
`/(!{1,'.count($this->level_classes).'})[ ]([^|<>\n]+)/`  
can be reduced to 
`(!{1,'.count($this->level_classes).'})[ ](.*)/` 
given that `$Line['text']` doesn't contain any `|` at the begining.

### Conclusion

I'm stuck. I can't fight the markdown engine and its connexion with the markdown-notice plugin.
I'm a bit sad that my researched ended in a dead-end.

**Comment by Romarain** [comment]
I just provide the complete code for tests, with capturing parenthesis references, for those who would like to try anything : 
```php
        $markdown->inlineNotices = function($Line)
        {
            $this->grav['debugger']->addMessage($Line['text']);
            $this->level_classes = $this->config->get('plugins.markdown-notices.level_classes');

            $foundedMatches = preg_match_all('/(!{1,'.count($this->level_classes).'})[ ]([^|<>\n]+)/', $Line['text'], $matches); // Original
            $foundedMatches = preg_match_all('/(\|[^\n])[ ]*(!{1,'.count($this->level_classes).'})[ ]([^|<>\n]+)/', $Line['text'], $matches); // Mod

            //$this->grav['debugger']->addMessage($Line['text']);

            if ( $foundedMatches > 0 )
            {
                echo "IT FOUND SOMETHIIIIIIIIIIING ";
                $level = strlen( $matches[1][0] ) - 1;
                $level = strlen( $matches[2][0] ) - 1; // Mod

                // if we have more levels than we support
                if ( $level > count( $this->level_classes ) - 1 )
                {
                    return;
                }

                $preText = explode( $Line['text'], $Line['context'], 2 );

                if ( strpos($Line['context'], $Line['text']) === 0 || rtrim( $preText[0] ) !== $preText[0] )
                {
                    $Block = [
                        'extent' => strlen( $matches[0][0] ),
                        'element' => [
                            'name' => 'div',
                            //'text' => $matches[2][0],
                            'text' => $matches[3][0], // Mod
                            'attributes' => [
                                'class' => 'notices ' . $this->level_classes[ $level ],
                            ],
                        ],
                    ];

                    return $Block;
                }
            }
        };
```

_Note : I didn't comment the original lines, I just added new ones right after, so they are rewriting things. Just swap them (CTRL+SHIFT+UP in Sublime-Text) for reversing._

**Comment by rhukster** [comment]
I've actually reverted PR#10 as it was also breaking multiline markdown notices.  releasing as 1.0.4
