### ISSUE TITLE
Not working in table cells

### ISSUE THREAD

**Issue by Sogl** [getgrav/grav-plugin-markdown-notices#15]
Hello!

Try to use inside tables:
```
| 1 | 2 | 3 |
| - | - | - |
| **4** | **5** | ! **6** |
| **7** | **8** | **9** |
| **10** | **11** | **12** |
| **13** | !! **14** | **15** |
```

Result:
![image](https://user-images.githubusercontent.com/7556290/65239129-f177bc00-dae6-11e9-81ae-50b747cc5d4d.png)

**Comment by rhukster** [comment]
That or was reverted as it broke things.

**Comment by Sogl** [comment]
Sad..
But your reply was quick 😄 👍
