### ISSUE TITLE
Plugin separating lines in separate divs

### ISSUE THREAD

**Issue by Verfallsdatum** [getgrav/grav-plugin-markdown-notices#2]
Hi, thanks for the plugin, it's really great!
Here's my problem: every return to the line is output in a separate div in the resulting HTML. This isn't the behavior explained in the documentation for the plugin (it says it should end up in a single bloc).
I'm having a hard time explaining so here's an example taking exactly the example given in the read me file of the plugin:
![image](https://cloud.githubusercontent.com/assets/16997095/12707425/3ac33812-c862-11e5-8e61-20ffc15442fc.png)
According to the documentation it should output this html:
![image](https://cloud.githubusercontent.com/assets/16997095/12707476/efe017d8-c862-11e5-8b3c-d57757e877e0.png)
But instead this is what I get:
![image](https://cloud.githubusercontent.com/assets/16997095/12707493/1ae6e8d0-c863-11e5-971d-5ff99fa328d4.png)
and the page looks messed up:
![image](https://cloud.githubusercontent.com/assets/16997095/12707506/352520fe-c863-11e5-9259-25e1213f78fc.png)

I'm using a (barely modified) version of antimatter, but I don't think it should cause any issue. Let me know if I'm not using the plugin properly. It looks almost right so I'd like to be able to use it.
thanks a lot

**Comment by rhukster** [comment]
Hmm.. I can confirm this is happening in my testing also.  It was working so something has broken it.  I will look into it. Thanks.

**Comment by rhukster** [comment]
Ah! I seemed to have jumped the gun on removing the link to 'my' forked version of parsedown. It was merged into dev-master but not released.  I've fixed the reference in our composer.json file and should be sorted in the upcoming update (next couple of days).

**Comment by Verfallsdatum** [comment]
Thank you for looking into this so quickly. I'll try it again as soon as it's updated in the repository then.
