### ISSUE TITLE
Fontawesome icons are not displayed

### ISSUE THREAD

**Issue by pmoreno-rodriguez** [getgrav/grav-plugin-markdown-notices#21]
Why aren't fontawsome icons showing in notice boxes?. In source code appears this:
class="sc-notice info", but the icon isn't showing.

![IMG_20211118_101731](https://user-images.githubusercontent.com/60596353/142387429-d77b3275-218c-47c4-bc31-6cf0b6129920.jpg)

**Comment by rhukster** [comment]
The plugin doesn't actually include any support for icons.  This example's icons and style are coming from the theme.  So probably a theme related issue.
