### ISSUE TITLE
How to add more colors?

### ISSUE THREAD

**Issue by sennewood** [getgrav/grav-plugin-markdown-notices#23]
I tried to add a new css class in `grav\user\plugins\markdown-notices\assets\notices.css` and a new entry in `grav\user\config\plugins\markdown-notices.yaml` - but the new color won't get rendered. Do I need to do something more/else or is it just not posssible?

**Comment by lilian-pouliquen** [comment]
Hi @sennewood!
I don't know if you're still looking for an answer. 
I was looking into the code and found out that it is possible to add colors by adding them into the config file and in the css built-in file (if you enabled it).

Ex: I want to add purple

```markdown-notices.yaml ```

```yaml
level_classes: [yellow, red, blue, green, purple]
```

```assets/notices.css```

```css
.notices.purple {
    border-left: 10px solid #a652ab;
    background: #f7f2fc;
    color: #a652ab;
}
```

Now to make a purple notice, I just need to include this in my Markdown:

```markdown
!!!!! This is a purple notice
```

![image](https://github.com/getgrav/grav-plugin-markdown-notices/assets/38006711/3345aef9-2b3b-49dc-abc2-ce055c22cf37)

**Comment by sennewood** [comment]
Thank you very much @lilian-pouliquen :)
