### ISSUE TITLE
Bullet points within markdown notices don't work

### ISSUE THREAD

**Issue by Verfallsdatum** [getgrav/grav-plugin-markdown-notices#3]
Hi.
I just noticed that bullet points are not displayed in published articles.
Here's my markdown text example:
![image](https://cloud.githubusercontent.com/assets/16997095/13242554/e6ed6d84-d9c3-11e5-9f2d-351f4d8844cd.png)
Same in preview mode:
![image](https://cloud.githubusercontent.com/assets/16997095/13242565/0ddc6864-d9c4-11e5-9402-c8e58dbb3c93.png)
But then when I publish:
![image](https://cloud.githubusercontent.com/assets/16997095/13242571/15805c2e-d9c4-11e5-837e-08ddb5290dc6.png)

weird... thanks for the help

**Comment by rhukster** [comment]
I'm guessing its a styling thing via CSS that is turning off the list style.  

Can you inspect it, or give me a URL i can look at to inspect it?

**Comment by Verfallsdatum** [comment]
Oh right, it's the materialize.css removing the list styling for some reason. Sorry, I should have checked before. I'm going to scrap that materialCSS framework from my custom theme anyway, I don't like it so much.
Thanks!
